package com.lsplogo.lexer;

// https://turtleacademy.com/playground for reference 

public enum TokenType {
    FORWARD, BACKWARD, LEFT, RIGHT,
    HOME, SETX, SETY, SETXY,
    SETH, ARC, ELLIPSE,

    POS, XCOR, YCOR,
    HEADING, TOWARDS,

    SHOWTURTLE, HIDETURTLE,
    CLEAN, CLEARSCREEN, FILL, FILLED,
    LABEL, SETLH, WRAP, WINDOW, FENCE,

    SHOWNP, LABELSIZE,

    PENUP, PENDOWN, SETCOLOR, SETWIDTH, CHANGESHAPE,

    PENDOWNP, PENCOLOR, PENSIZE,

    TO, DEFINE, DEF, END,

    MAKE, NAME, LOCALMAKE, THING,

    REPEAT, FOR, REPCOUNT, IF, IFELSE, TEST,
    IFTRUE, IFFALSE, WAIT, BY, DOTIMES,
    DOWHILE, WHILE, DOUNTIL, UNTIL,

    LIST, FIRST, BUTFIRST, LAST, BUTLAST,
    ITEM, PICK,

    SUM, MINUS, RANDOM, MODULO, POWER,

    READWORD, READLIST,

    NUMBER,
    STRING,

    IDENTIFIER,
    VARIABLE,

    PLUS, MINUS_OP, ASTERISK, SLASH, EQUALS, LESS, GREATER,

    LBRACKET, RBRACKET,
    LPAREN, RPAREN,

    EOF,
    NEWLINE,
    COMMENT,
    ERROR
}
